#!/bin/bash

###
# OpenZula server utilities
#
# Copyright (c) 2011 Alex Cartwright <alex@openzula.org>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name(s) of the above
# copyright holders shall not be used in advertising or otherwise
# to promote the sale, use or other dealings in this Software without
# prior written authorization.
###

scriptName=$(basename $0)
scriptDir=$(dirname $0)
configPath=./config
configFile=$configPath/config.cfg

showHelp()
{
	echo "OpenZula server utilities"
	echo -e "Usage:\n\t$scriptName [backup|details|domain|email|list]\n"
	echo "Options:"
	echo -e "\t-v\tVersion information"
	echo -e "\t-h\tDisplays this help text, or help for each action e.g. $scriptName domain -h\n"
	echo "Report bugs to <alex@openzula.org>"
}

if (( $(id -u) > 0 )); then
	echo "Please run this script as root." >&2
	exit 2
fi

if [[ -f $configFile ]]; then
	source "$configFile"

	## Ensure the var state directory exists
	if [[ ! -d $cfgVarStateDir ]]; then
		mkdir -p "$cfgVarStateDir"
	fi

	## Ensure that some variables have a default value
	if [[ -f /etc/adduser.conf ]]; then
		source /etc/adduser.conf

		cfgUsersHomeDir=${cfgUsersHomeDir:-$DHOME}
		cfgUsersHomeDirMode=${cfgUsersHomeDirMode:-$DIR_MODE}
		cfgUsersShell=${cfgUsersShell:-$DSHELL}
	else
		cfgUsersHomeDir=${cfgUsersHomeDir:-/home}
		cfgUsersHomeDirMode=${cfgUsersHomeDirMode:-0750}
		cfgUsersShell=${cfgUsersShell:-/bin/bash}
	fi

	## Source the LDAP functions ready to use
	if [[ $cfgLdapEnable = true ]]; then
		source "$scriptDir/ldapfuncs"
	fi
else
	echo "Unable to find config file '$configFile'" >&2
	exit 2
fi

if (( $# == 0 )); then
	showHelp
	exit 0
fi

case $1 in
	backup|details|domain|email|list)
		source "$scriptDir/actions/$1"
		;;
	-v)
		echo "0.9.91"
		;;
	-h)
		showHelp
		exit 1
		;;
	*)
		echo "Invalid argument '$1'. See '-h' for help text." >&2
		exit 1
		;;
esac

exit 0
