#!/bin/bash

##
## post-domain-enable
## Enables the Apache2 vhost
##

if ! type a2ensite &> /dev/null; then
	echo "post-domain-enable/apache2: 'a2ensite' was not found or does not exist" >&2
	exit 2
elif ! a2ensite "$OZ_DOMAIN_NAME" > /dev/null; then
	echo "post-domain-enable/apache2: failed to enable domain '$OZ_DOMAIN_NAME'" >&2
	exit 2
fi
