#!/bin/bash

###
# OpenZula server utilities
# --- Gets credentials/details of domains and email addresses
#
# Copyright (c) 2011 Alex Cartwright <alex@openzula.org>
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# Except as contained in this notice, the name(s) of the above
# copyright holders shall not be used in advertising or otherwise
# to promote the sale, use or other dealings in this Software without
# prior written authorization.
###

case $2 in
	--domain)
		action=domain
		getoptsStr=":d:h"
		;;
	--email)
		action=email
		getoptsStr=":a:h"
		;;
	-h)
		echo "OpenZula server utilities"
		echo "Usage:"
		echo -e "\t$scriptName details --domain -d domain"
		echo -e "\t$scriptName deatils --email -a foo@example.com\n"
		echo "Report bugs to <alex@openzula.org>"
		exit 0
		;;
	*)
		echo "Invalid action '$2'. Use '--domain' or '--email'" >&2
		exit 1
		;;
esac

shift 2
while getopts $getoptsStr OPTION
do
	case $OPTION in
		a)
			optEmail=$OPTARG
			;;
		d)
			if [[ $OPTARG =~ ^www\. ]]; then
				optDomain=${OPTARG:4}
			else
				optDomain=$OPTARG
			fi
			;;
		h)
			echo "OpenZula server utilities"
			echo "Usage:"
			if [[ $action = domain ]]; then
				echo -e "\t$scriptName details --domain -d domain\n"
				echo "Options:"
				echo -e "\t-d\tDomain name of the website to get details for."
			elif [[ $action = email ]]; then
				echo -e "\t$scriptName details --email -a foo@example.com\n"
				echo "Options:"
				echo -e "\t-a\tEmail address to get details for."
			fi
			echo -e "\t-h\tDisplays this help text.\n"
			echo "Report bugs to <alex@openzula.org>"
			exit 0
			;;
		*)
			echo "Invalid argument (or value of) '-$OPTARG'. See '-h' for help text." >&2
			exit 1
			;;
	esac
done

if [[ -z $optDomain && -z $optEmail ]]; then
	if [[ $action = domain ]]; then
		echo "Invalid arguments; expecting at least '-d'. See -'h' for help text." >&2
	else
		echo "Invalid arguments; expecting at least '-a'. See -'h' for help text." >&2
	fi
	exit 1
fi

## Output the correct credentials file if it exists
if [[ $action = domain ]]; then
	credentialsFile=$cfgVarStateDir/domains/$optDomain
else
	credentialsFile=$cfgVarStateDir/emails/$optEmail
fi

if [[ -f $credentialsFile ]]; then
	cat "$credentialsFile"
else
	echo "Unable to find '$credentialsFile'" >&2
	exit 2
fi

exit 0