#!/bin/bash

##
## post-domain-add
## Creates a new Apache2 vhost using the template "apache2-vhost-template" and
## then enables this vhost. We don't however restart Apache with this, it's
## recommended you do this your self manually when you're ready.
##
## The template file can have the following variables that get replace:
##
##    {USER}		username
##    {DOMAIN}		domain name
##    {DOMAIN_PATH}	Path to the domain (*not* the document root)
##

if [[ -f apache2-vhost-template ]]; then
	sed -e "s/{USER}/$OZ_USER/g" \
		-e "s/{DOMAIN}/$OZ_DOMAIN_NAME/g" \
		-e "s|{DOMAIN_PATH}|$OZ_DOMAIN_PATH|g" \
		apache2-vhost-template > "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"
	a2ensite "$OZ_DOMAIN_NAME" > /dev/null
	exit 0
else
	echo "'apache2-vhost-template' does not exist, unable to create vhost config" >&2
	exit 2
fi