#!/bin/bash

##
## post-domain-add
## Creates the PHP-FPM configuration file for the new domain using the template
## "apache2-vhost-template". php53-fpm is then reloaded once created.
##
## The template file can have the following variables that get replace:
##
##    {USER}		username
##    {DOMAIN}		domain name
##    {DOMAIN_PATH}	Path to the domain (*not* the document root)
##

if [[ ! -f /etc/init.d/php53-fpm ]]; then
	echo "post-domain-add/php-fpm: '/etc/init.d/php53-fpm' does not exist" >&2
	exit 2
elif [[ ! -f php-fpm-template ]]; then
	echo "post-domain-add/php-fpm: 'php-fpm-template' does not exist" >&2
	exit 2
fi

sed -e "s/{USER}/$OZ_USER/g" \
	-e "s/{DOMAIN}/$OZ_DOMAIN_NAME/g" \
	-e "s|{DOMAIN_PATH}|$OZ_DOMAIN_PATH|g" \
	php-fpm-template > "/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf"

/etc/init.d/php53-fpm reload > /dev/null