#!/bin/bash

##
## post-domain-add
## If you use Git to keep track of /etc (highly advised!) then this will automatically
## commit the correct changes so you can easily see what has happened when a
## new domain was added and be able to do all the lovely Git things with it.
##

if type git &> /dev/null && [[ -d /etc/.git ]]; then
	gitAuthorName=${SUDO_USER:-root}
	export GIT_DIR=/etc/.git GIT_WORK_TREE=/etc/
	git add "/etc/apache2/sites-available/$OZ_DOMAIN_NAME"\
			"/etc/apache2/sites-enabled/$OZ_DOMAIN_NAME"\
			"/etc/opt/php53/fpm.d/$OZ_DOMAIN_NAME.conf"\
			/etc/group\
			/etc/gshadow\
			/etc/passwd\
			/etc/shadow > /dev/null
	git commit --author="$gitAuthorName <$gitAuthorName@$(hostname -f)>" -m "ozsrvutils/domain/add: $OZ_DOMAIN_NAME" > /dev/null
fi

exit 0